version: '3'
services:
  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=cedtjobfair
    ports:
      # left is host, right is container
      - "8090:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: